#' Process the output generated by \code{query_genomes_to_modules()}.
#'
#' @param FRACTION_MATRIX      - matrix. $MATRIX matrix generated by \code{query_genomes_to_modules()}.
#'
#' @param QUERIES              - optional. $QUERIES data frame generated by \code{query_genomes_to_modules()} containing the search query performed.
#'
#' @param outPath              - optional. String to indicate path to store output file and figures. Default (\code{Sys.Date()} as 'YYYY_MM_DD', e.g. '2000_01_31').
#'
#' @param report_file          - optional. File name for LaTex report (see \code{Details} for path handling). Default ("report.tex" saved to outPAth; use \code{NULL} to supress report generation).
#'
#' @param figType              - optional. Character vector to indicate file extension for figures. Default (c(".eps", ".png")).
#'
#' @param FACTOR               - optional. Character vector or list of character vectors indicating the grouping factor of the datasets. Default (\code{NULL}).See \code{Details}.
#'
#' @param ...                  - further arguments for \link{analysis_pca_mean_distance_grouping} or argument { }{ }\code{factor_labs} for \link{plot_scatter_byFactors}.
#'
#' @details
#' Below are the steps carried on the \code{query_genomes_to_modules()} output.
#'
#' (1) Module fraction completeness (mfc) visualization of the \code{query_genomes_to_modules()} output; generates file: module_allOrgs\code{.figType}.
#'
#' (2) variance analysis to identify complete and absent modules,
#' as well as modules with zero variance (i.e. same fraction present across all modules);
#' generates files: module_allOrgs_sd\code{.figType}, module_allOrgs_sd_boxplot\code{.figType} and module_constant_presence.txt.
#'
#' (3) a principal component analysis (PCA; using the \code{prcomp} from the 'stats' package) is done
#' and a plot of the cumulative variance and the first to principal components are generated;
#' generates files in PCA/ : pca_plot\code{.figType}, pca_sd\code{.figType} and pca.rda
#'
#' When \code{FACTOR} is specified, a mean distance is calculated as a proxy for inner-group spread
#' (using as many dimensions as specified by the optional additional argument \code{nDim}; used by \link{analysis_pca_mean_distance_grouping()}).
#' This generates additional files: module_mean_dist_output_FACTOR.rda and the following for each factor (multiple factors possible if \code{FACTOR} is a list):
#'
#' module_<FACTOR>_mean.png,module_<FACTOR>_sd\code{.figType}, PCA/plot_mean_dist_<FACTOR>\code{.figType} and PCA/plot_scatter_<FACTOR>\code{.figType}
#'
#' It will be assumed that if \code{report_file} has a folder structure (identified by "\\") a path has been given.
#' Otherwise, the report will be written to \code{outPath}. If \code{report_file} is set to \code{NULL}, the report is not generated.
#'
#' @return
#' This function does not return anything, but does generate multiple files (see \code{Details}).
#' This function automatically generates a ".tex" file (LaTex report), which can be externally processed to generate a PDF file, unless \code{report_file} is set to \code{NULL}.
#'
#' ggplot objects for all figures are generated and saved in an R object ("module_output_plots.rda") within the output directory.
#'
#' @export
#'
#' @seealso \link{query_genomes_to_modules}, \link{analysis_pca_mean_distance_grouping},\link{plot_heatmap}
#'

############################################################################################################################################

analysis_genomes_module_output <- function(FRACTION_MATRIX,QUERIES = NULL,outPath = "",report_file = "report.tex",figType = c(".eps",".png"),FACTOR = NULL,...){
                                           # byGenus = FALSE,bySpecies = FALSE,

### MANAGE INPUT ----

  if(outPath == ""){
    outPath <- as.character(gsub("-","_",Sys.Date()))
  } else {
    outPath <- gsub("^/","",outPath)
    outPath <- gsub("/$","",outPath)
  }

  if(!dir.exists(outPath)){
    dir.create(outPath)
  }

  # stopifnot(is.logical(byGenus),is.logical(bySpecies))

  # REPORT
  if(!is.null(report_file)&&is.character(report_file)){
    if(length(report_file)>1) report_file <- report_file[1]

    # IF report_file HAS FOLDER STRUCTURE USE AS PATH.
    if(length(grep("/",report_file))>0){
      report_PATH     <- report_file
      finalise_report <- FALSE # assume it will be finalised when it is finished being processed
    # OTHERWISE, WRITE IT IN outPath
    } else{
      report_file     <- gsub(outPath,"",report_file)
      report_PATH     <- paste(outPath,"/",report_file,sep="")
      finalise_report <- TRUE # assume it will not be used downstream
    }
    # cat("report_PATH", report_PATH, fill = T)
    if(length(grep(".tex$",report_PATH))==0){
      report_PATH <- gsub('[.][a-z]+$',"",report_PATH)
      report_PATH <- paste(report_PATH,".tex",sep="")
    }
    REPORT          <- TRUE
  } else {
    REPORT          <- FALSE
    finalise_report <- FALSE
  }

  # Figure file extension(s)
  index <- which((substr(figType,1,1)!="."))
  if(length(index)>0) figType[index] <- paste("",figType[index], sep="")

  # Figure file extension for report
  if(length(figType)>1) {
    if(length(which(figType==".pdf"))>0){
      figType_report <- ".pdf"
    }else{
      if(length(which(figType==".png"))>0){
        figType_report <- ".png"
      }else{
        figType_report <- figType[1]
      }
    }
  } else {
    figType_report <- figType
  }

  # CHECK MATRIX ROWNAMES
  DATASETS <- misc_check_duplicate_names(rownames(FRACTION_MATRIX))
  rownames(FRACTION_MATRIX) <- DATASETS

  # CATCH OTHER ARGUMENTS...
  arguments <- list(...)

  # REFERENCE DATA
  # devtools::use_data(module_reference_table,overwrite = T)

####### REPORT #######
# INITIATE REPORT FILE
  if(REPORT){
    text_init <- c('\\documentclass{article} ',
                   "\\usepackage[top=1in, bottom=1.25in, left=1.25in, right=1.25in]{geometry}",
                    "% FIGURE PACKAGES",
                    "\\usepackage{graphicx} \\usepackage{caption} \\usepackage{subcaption}\\usepackage[section]{placeins}",
                    "% MATHS PACKAGES",
                    "\\usepackage{amsmath}",
                    "%Begin document",
                    "\\begin{document}",
                    "\\title{Module output: report}",
                    "\\maketitle\n")
    write(text_init,file = report_PATH,append = FALSE)


  write("\\section*{Module Analysis}\n",file = report_PATH,append = TRUE)

  if(!is.null(QUERIES)){
    TEXT <- xtable::xtable(QUERIES,caption = "Module analysis queries. If all are '$<>$', the default is to analyse all modules not defined by other modules.",
                           label = "tab:Queries",align = c("p{0.5cm}","p{3.5cm}","p{11.5cm}"))
    xtable::print.xtable(TEXT, file = report_PATH, append = T,include.rownames = FALSE)
  }

  }
### PROCESS AND VISUALICE RAW DATA ----

  # HEATMAP
  P_allOrgs <- plot_heatmap(FRACTION_MATRIX,Filename = paste(outPath,"/module_allOrgs",figType,sep=""))

####### REPORT
  ## GET NUMBER OF 'EMPTY' DATASETS AND CONSTANT [VARIANCE] MODULES ----
  sum <- apply(FRACTION_MATRIX,1,sum)
  sd  <- apply(FRACTION_MATRIX,2,sd)

  # NUMBER OF DATASETS AND MODULES ANALYSED
  if(REPORT){
    write("\\subsection*{Data set and modules summary}",file = report_PATH,append = TRUE)

    write("\\begin{itemize}",file = report_PATH, append = T)
    ## DATASETS
    write(paste("\\item",dim(FRACTION_MATRIX)[1], "data sets\\\\"),file = report_PATH, append = T)

    ## EMPTY DATASETS
    write(paste("\\item",length(which(sum==0)),"datasets without any module fraction match\\\\"),file = report_PATH, append = T)

    ### MODULES
    write(paste("\\item",dim(FRACTION_MATRIX)[2], "modules analysed initially\\\\"),file = report_PATH, append = T)
    write("\\end{itemize}",file = report_PATH, append = T)
  }


  ## VARIANCE ----
  P_allOrgs_sd_boxplot <- plot_variance_boxplot(FRACTION_MATRIX, Filename =paste(outPath,"/module_allOrgs_sd_boxplot",figType,sep=""))

  modules_sd           <- data.frame(Modules = colnames(FRACTION_MATRIX)[order(sd)],
                            Var = 1,
                            StDev = sd[order(sd)],
                            stringsAsFactors = F)
  P_allOrgs_sd <- plot_scatter(modules_sd,xLab = "Modules",yLab = "Standard deviation",
                                Filename = paste(outPath,"/module_allOrgs_sd",figType,sep=""))


  ### REPORT IT ----
  # ADD PLOTS TO REPORT
  if(REPORT){
    write("\\subsubsection*{Module fraction presence: heatmap and variance}",file = report_PATH,append = TRUE)
    # write("Heatmap and variance plots of all data sets across all analysed modules",file = report_PATH, append = T)
    FILES     <- c(paste(outPath,"/module_allOrgs",figType_report,sep=""),             # module heatmap
               paste(outPath,"/module_allOrgs_sd_boxplot",figType_report,sep=""), # module box plot
               paste(outPath,"/module_allOrgs_sd",figType_report,sep=""))                    # module variance scatter plot
    Captions  <- c("Module fraction presence across data sets",
                   "Module fraction presence variance - boxplot",
                   "Module fraction presence variance - scatter plot")
    FIGURE    <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",
                       FILES,"}\n\\caption{",Captions,"}\\label{fig:",FILES,"}\\end{figure}",sep="")
    write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)
  }

  # MEAN AND VARIANCE BY FACTOR ----
  if(!is.null(FACTOR)){
    if(length(which(names(arguments)=="factor_labs"))==0){
      if(is.null(names(FACTOR))){
        factor_labs <- paste("factor",1:length(FACTOR),sep="")
      }else{
        factor_labs <- names(FACTOR)
      }
    }

    # KEEP MODULES WITH NO ZERO VARIANCE
    module_matrix_subset <- FRACTION_MATRIX[,which(apply(FRACTION_MATRIX,2,sum)>0)]

    for(G in 1:length(FACTOR)){
      this_factor <- FACTOR[[G]]
      ## CHECK DIMENSIONS
      # if(length(this_factor)==1&&this_factor=="") warning(paste("Factor",G,"empty")); next
      if(length(this_factor)!=nrow(FRACTION_MATRIX)){
        warning(paste("Incorrect length for factor",G,"-",length(this_factor),"instead of",nrow(FRACTION_MATRIX)))
        next
      }

      Groups              <- sort(unique(this_factor))
      nGroups             <- length(Groups)
      mean_matrix         <- matrix(nrow = nGroups, ncol = ncol(module_matrix_subset))
      sd_matrix           <- matrix(nrow = nGroups, ncol = ncol(module_matrix_subset))
      rownames(mean_matrix) <- Groups
      rownames(sd_matrix) <- Groups
      colnames(mean_matrix) <- colnames(module_matrix_subset)
      colnames(sd_matrix) <- colnames(module_matrix_subset)

      # REMOVE GROUPS WITH SINGLE MEMBER
      remove_index <- NULL
      for(n in 1:nGroups){
        group_index <- which(this_factor == Groups[n])
        if(length(group_index)>1){
          for(i in 1:ncol(module_matrix_subset)) mean_matrix[n,i] <- mean(module_matrix_subset[group_index,i])
          sd_matrix[n,]   <- apply(module_matrix_subset[group_index,],2,sd)
        }else{
          remove_index <- c(remove_index,n)
        }
      }

      # Matrix with variance for the groups with more than one member
      if(length(remove_index)>0){
        mean_matrix <- mean_matrix[-remove_index,]
        sd_matrix   <- sd_matrix[-remove_index,]
      }

      if(sum(dim(sd_matrix)>0)>1){
        plot <- plot_heatmap(mean_matrix,Filename = paste(outPath,"/module_mean_",factor_labs[G],figType,sep=""),set_yLim = T)
        plot <- plot_heatmap(sd_matrix,Filename = paste(outPath,"/module_sd_",factor_labs[G],figType,sep=""),set_yLim = T,legend_name = "sd\n")
      } else{
        # cat("FACTOR",G,"nGroups",nGroups,"dim(sd_matrix)",dim(sd_matrix),fill = T)
        warning(paste("No groups in FACTOR ",G,"(",factor_labs[G],"). No variance plot produced.",sep=""))
      }
    }

    ### REPORT IT ----
    # ADD PLOTS TO REPORT
    if(REPORT){
      write("\\subsubsection*{Module fraction presence: mean and variance by grouping factors}",file = report_PATH,append = TRUE)
      FILES <- NULL
      # for(FT in figType_report)
        # MEAN
        FILES     <- paste(outPath,"/module_mean_",factor_labs,figType_report,sep="")
        Captions  <- paste(factor_labs,": mcf - mean",sep="")
        FIGURE    <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                         "}\\label{fig:",FILES,"}\\end{figure}",sep="")
        write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)

        # SD
        FILES     <- paste(outPath,"/module_sd_",factor_labs,figType_report,sep="")
        Captions  <- paste(factor_labs,": mcf - standard deviation",sep="")
        FIGURE    <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                          "}\\label{fig:",FILES,"}\\end{figure}",sep="")
        write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)
    }
  }# MEAN AND VARIANCE BY FACTOR

### Variance ----
  # devtools::use_data(module_reference_table)
  # Find complete and absent modules present across ALL genomes
  complete_module_index <- which(apply(FRACTION_MATRIX,2,sum)==dim(FRACTION_MATRIX)[1])
  complete_module_names <- names(complete_module_index)
  absent_module_index   <- which(apply(FRACTION_MATRIX,2,sum)==0)
  absent_module_names   <- names(absent_module_index)

  if(length(grep("M\\d{5}",names(FRACTION_MATRIX)))>0){
    ref_col <- which(names(module_reference_table)=="ID")
  } else {
    ref_col <- which(names(module_reference_table)=="NAME_SHORT")
  }

  ### FIND complete & absent modules ----
  # COMPLETE
  REF_complete_module_index <- sort(match(complete_module_names,module_reference_table[,ref_col]))  # 760 total modules
  complete_modules <- dplyr::select(module_reference_table[REF_complete_module_index,],ID,NAME_SHORT,NAME,CLASS_I,CLASS_II,CLASS_III)
    # write.table(complete_modules,gsub("//","/",paste(outPath,"/complete_modules_",useDate,"_",appendFileName,".txt",sep="")),sep = "\t",row.names = F)
  # ABSENT
  REF_absent_module_index <- sort(match(absent_module_names,module_reference_table[,ref_col]))  # 760 total modules
  absent_modules <- dplyr::select(module_reference_table[REF_absent_module_index,],ID,NAME_SHORT,NAME,CLASS_I,CLASS_II,CLASS_III)

  # THOSE WITH 0 VARIANCE!!!! CONSTANT ACROSS GENOMES
  variance      <- apply(FRACTION_MATRIX,2,sd)

  # REMOVE THOSE THAT ARE COMPLETE OR ABSENT ACROSS ALL GENOMES!
  zero_variance_index   <- setdiff(which(variance==0),c(absent_module_index,complete_module_index))
  zero_variance_names   <- colnames(FRACTION_MATRIX)[zero_variance_index]
  if(length(zero_variance_index)>0){
    REF_zero_variance_index <- sort(match(zero_variance_names,module_reference_table[,ref_col]))  # 760 total modules
    zero_variance_modules <- dplyr::select(module_reference_table[REF_zero_variance_index,],ID,NAME_SHORT,NAME,CLASS_I,CLASS_II,CLASS_III)
      # write.table(zero_variance_modules,gsub("//","/",paste(outPath,"/modules_zero_sd_",useDate,"_",appendFileName,".txt",sep="")),sep = "\t",row.names = F)
  } else {
    zero_variance_modules <- NULL
  }

### REMOVE COMPLETE, ABSENT AND ZERO VARIANCE MODULES ----
  remove_modules                  <- sort(c(complete_module_index,absent_module_index,zero_variance_index))
  if(length(remove_modules)>0) {
    FRACTION_MATRIX_Subset <- FRACTION_MATRIX[,-remove_modules]

    ### VARIANCE OUTPUT TABLE ----
    module_zero_var <- NULL
    if(dim(complete_modules)[1]>0)      module_zero_var <- rbind(module_zero_var,as.matrix(cbind(rep("complete",nrow(complete_modules)),complete_modules)))
    if(dim(absent_modules)[1]>0)        module_zero_var <- rbind(module_zero_var,as.matrix(cbind(rep("absent",nrow(absent_modules)),absent_modules)))
    if(!is.null(zero_variance_modules)) module_zero_var <- rbind(module_zero_var,as.matrix(cbind(rep("zero_var",nrow(zero_variance_modules)),zero_variance_modules)))

    ### WRITE REPORT ----
    if(REPORT){
      TEXT  <- paste("\\subsubsection*{Zero variance}\nIdentify modules that are complete, absent or that are constant (zero variance) across all data sets (see module\\_presence.rda)\\\\")
      write(TEXT,file = report_PATH, append = T)
    }

    if(!is.null(module_zero_var)){
      module_zero_var <- as.data.frame(module_zero_var,stringsAsFactors = F)
      names(module_zero_var) <- c("module_status",names(complete_modules))
      # write.table(module_zero_var,paste(outPath,"/module_constant_presence.txt",sep=""),sep = "\t",row.names = F,quote = F)

      ### WRITE REPORT ----
      if(REPORT){
        TEXT  <- paste("There are",nrow(module_zero_var), "modules with zero variance of the following types:")
        write(TEXT,file = report_PATH, append = T)

      # TYPES OF ZERO VARIANCE
      types <- unique(module_zero_var[,1])
      # for(ii in types) cat("\t\t\t",ii, "-", length(which(module_zero_var[,1]==ii)), fill = T)
      write("\\begin{itemize}",file = report_PATH, append = T)
      for(ii in types) write(paste("\\item",ii, "$-$", length(which(module_zero_var[,1]==ii)),"\\\\"),file = report_PATH, append = T)
      write("\\end{itemize}",file = report_PATH, append = T)
      }
      save(module_zero_var,file = paste(outPath,"/module_zero_var.rda",sep=""))

      # WRITE FACTOR TABLE
      if(REPORT){
        if(dim(module_zero_var)[1]<20){
        TEXT <- xtable::xtable(module_zero_var[,1:3],caption = "Module presence",label = "tab:module_zero_var",align = c("p{0.5cm}","p{2.5cm}","p{2.5cm}","p{9cm}"))
        xtable::print.xtable(TEXT, file = report_PATH, append = T,include.rownames = FALSE)
        }
      }
    }

    if(dim(FRACTION_MATRIX_Subset)[2]>0){
      variance_Subset             <- apply(FRACTION_MATRIX_Subset,2,sd)
      FRACTION_MATRIX_Subset <- FRACTION_MATRIX_Subset[,order(variance_Subset)]

      P_allOrgs_Subset     <- plot_heatmap(FRACTION_MATRIX_Subset,Filename = paste(outPath,"/module_allOrgs_subset",figType,sep=""))

      # ADD PLOTS TO REPORT
      if(REPORT){
        write("Heatmap and variance plots of all data sets across all non zero-variance modules (modules subset).",file = report_PATH, append = T)
        FILES <- c(paste(outPath,"/module_allOrgs_subset",figType_report,sep=""))
        Captions <- c("Modules subset (zero variance removed)","Modules subset (zero variance removed) variance")
        FIGURE <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                        "}\\label{fig:",FILES,"}\\end{figure}",sep="")
        write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)
      }
    }
  } else {
    ### WRITE REPORT ----
    if(REPORT){
      TEXT  <- paste("No modules with zero variance.\\\\")
      write(TEXT,file = report_PATH, append = T)

      module_zero_var <- "No zero variance modules"
      write("No modules found to be constant (i.e. complete, absent or with zero variance across all genomes).",
            file = paste(outPath,"/module_constant_presence.txt",sep=""))
      write("Genomes analysed:",append = T,
            file = paste(outPath,"/module_constant_presence.txt",sep=""))
      write(paste("\t",DATASETS,collapse = "\n"),append = T,
            file = paste(outPath,"/module_constant_presence.txt",sep=""))
    }
  }

# ### BY GENUS ANALYSIS ----
#   if(byGenus){
#     genus <- NULL
#     for(G in DATASETS) genus <- c(genus,strsplit(G,split =" ")[[1]][1])
#     genus                       <- unique(genus)
#     module_matrix_byGenus       <- matrix(nrow = length(genus),ncol = ncol(FRACTION_MATRIX))
#     genus_sd_matrix            <- matrix(nrow = length(genus),ncol = ncol(FRACTION_MATRIX))
#     rownames(genus_sd_matrix)  <- rownames(module_matrix_byGenus) <- genus
#     colnames(genus_sd_matrix)  <- colnames(module_matrix_byGenus) <- colnames(FRACTION_MATRIX)
#
#     for(G in 1:length(genus)){
#       index <- grep(genus[G],DATASETS)
#       if(length(index)>1){
#         module_matrix_byGenus[G,] <- apply(FRACTION_MATRIX[index,],2,mean)
#         genus_sd_matrix[G,]      <- apply(FRACTION_MATRIX[index,],2,sd)
#       }else{
#         module_matrix_byGenus[G,] <- FRACTION_MATRIX[index,]
#       }
#     }
#
#     P_genus     <- plot_heatmap(module_matrix_byGenus,Filename = paste(outPath,"/module_byGenus_mean",figType,sep=""))
#
#     # BOXPLOT FOR VARIANCE
#     P_genus_sd <- plot_heatmap(genus_sd_matrix, Filename =paste(outPath,"/module_byGenus_sd",figType,sep=""),legend_name = "sd\n")
#
#     ##### WRITE byGenus DATA
#     fileName <- paste(outPath,"/modules_byGenus.txt",sep="")
#     rownames(genus_sd_matrix) <- paste(rownames(genus_sd_matrix),"_sd",sep="")
#     modules_byGenus <- rbind(module_matrix_byGenus,genus_sd_matrix)
#     # SAVE R OBJECT
#     save(modules_byGenus,file = gsub(".txt",".rda",fileName))
#     # WRITE FILE
#     # View(modules_byGenus)
#     # HEADER
#     write(x = paste(c("Dataset",colnames(modules_byGenus)),collapse = "\t"),file = fileName,append = F)
#     for(L in 1:nrow(modules_byGenus)) write(x = paste(c(rownames(modules_byGenus)[L],modules_byGenus[L,]),collapse = "\t"),file = fileName,append = T)
#   }else{
#     P_genus <- P_genus_sd <- "No genus analysis carried out"
#   }
#
# ### BY SPECIES ANALYSIS ----
#   if(bySpecies == T){
#     species <- NULL
#     for(G in DATASETS) species <- c(species,paste(strsplit(G,split =" ")[[1]][1:2],collapse = " "))
#     species                       <- unique(species)
#     module_matrix_bySpecies       <- matrix(nrow = length(species),ncol = ncol(FRACTION_MATRIX))
#     species_sd_matrix            <- matrix(nrow = length(species),ncol = ncol(FRACTION_MATRIX)) # DATA == NA
#     rownames(species_sd_matrix)  <- rownames(module_matrix_bySpecies) <- gsub(" ","_",species)
#     colnames(species_sd_matrix)  <- colnames(module_matrix_bySpecies) <- colnames(FRACTION_MATRIX)
#
#     for(G in 1:length(species)){
#       index <- grep(species[G],DATASETS)
#       if(length(index)>1){
#         module_matrix_bySpecies[G,] <- apply(FRACTION_MATRIX[index,],2,mean)
#         species_sd_matrix[G,]      <- apply(FRACTION_MATRIX[index,],2,sd)
#       }else{
#         module_matrix_bySpecies[G,] <- FRACTION_MATRIX[index,]
#       }
#     }
#
#     P_species     <- plot_heatmap(module_matrix_bySpecies,Filename = paste(outPath,"/module_bySpecies_mean",figType,sep=""))
#
#     # BOXPLOT FOR VARIANCE
#     P_species_sd <- plot_heatmap(species_sd_matrix, Filename =paste(outPath,"/module_bySpecies_sd",figType,sep=""),legend_name = "sd\n")
#
#     ##### WRITE bySpecies DATA
#     fileName <- paste(outPath,"/modules_bySpecies.txt",sep="")
#     rownames(species_sd_matrix) <- paste(rownames(species_sd_matrix),"_sd",sep="")
#     modules_bySpecies <- rbind(module_matrix_byGenus,species_sd_matrix)
#     # WRITE R OBJECT
#     save(modules_bySpecies,file = gsub(".txt",".rda",fileName))
#     # WRITE FILE
#     write(x = paste(c("Dataset",colnames(modules_bySpecies)),collapse = "\t"),file = fileName,append = F)
#     for(L in 1:nrow(modules_bySpecies)) write(x = paste(c(rownames(modules_bySpecies)[L],modules_bySpecies[L,]),collapse = "\t"),file = fileName,append = T)
#
#   }

### PCA ----
  if(!dir.exists(paste(outPath,"/PCA",sep=""))) dir.create(paste(outPath,"/PCA",sep=""))

  pca <- prcomp(FRACTION_MATRIX)
  save(pca,file = paste(outPath,'/PCA/pca.rda',sep=""))

  # Variance fraction captured in each principal component ----
  var <- pca$sdev^2
  var_total <- sum(var)
  var_frac <- var/var_total
  # Cumulative variance ----
  cum_var <- numeric(length(var_frac)) # 0 0 0 0
  cum_var[1] <- var_frac[1]
  for(ii in 2:length(var)){
    cum_var[ii] <- sum(var_frac[ii]+cum_var[ii-1])
  }

  ### PLOT CUMULATIVE VARIATION ----

  for(FT in figType){
    File <- paste(outPath,'/PCA/pca_var',FT,sep="")
    # pdf(file = paste(outPath,'/PCA/pca_var.pdf',sep=""))
    if(length(grep("pdf",FT)>0)){
      pdf(file = File,width = 7,height = 7)
    }else if(length(grep("png",FT)>0)){
      png(filename = File,width = 7,height = 7,units = "in",res = 250)
    }else if(length(grep("svg",FT)>0)){
      svg(filename = File,width = 7,height = 7)
    }else if(length(grep("jpeg",FT)>0)){
      jpeg(filename = File,width = 7,height = 7,units = "in",res = 250)
    }
    plot(1:length(cum_var),cum_var,type = "l",xlab = paste("Principal components (",length(cum_var),")",sep=""),
         ylab = "Cumulative variation",col = 'black',lwd = 2,ylim = c(min(cum_var)*0.90,max(cum_var)))
    # ADD LINE TO INIDICATE WHEN 90%OF THE VARIANCE HITS
    var_90_index <- which(cum_var>0.9)[1]
    points(c(var_90_index,var_90_index),c(min(cum_var),cum_var[var_90_index]),type = "l",col = "red",lwd = 2)
    text(var_90_index,cum_var[var_90_index]*1.05,labels = "90%",col = "red")
    text(var_90_index,min(cum_var)*0.95,labels = var_90_index,  col = "red")
    dev.off()
  }

  ### PLOT PC1 v PC2 ----
  for(FT in figType){
    File <- paste(outPath,'/PCA/pca_plot',FT,sep="")
    # pdf(file = paste(outPath,'/PCA/pca_var.pdf',sep=""))
    if(length(grep("pdf",FT)>0)){
      pdf(file = File,width = 7,height = 7)
    }else if(length(grep("png",FT)>0)){
      png(filename = File,width = 7,height = 7,units = "in",res = 250)
    }else if(length(grep("svg",FT)>0)){
      svg(filename = File,width = 7,height = 7)
    }else if(length(grep("jpeg",FT)>0)){
      jpeg(filename = File,width = 7,height = 7,units = "in",res = 250)
    }
    # pdf(file = paste(outPath,'/PCA/pca_plot.pdf',sep=""))
    plot(pca$x,xlab = paste("PC1 (",format(pca$sdev[1]*100,digits = 4),"%)",sep=""),ylab = paste("PC2 (",format(pca$sdev[2]*100,digits = 4),"%)",sep=""),pch = 16) # PC1 v PC2
    dev.off()
  }


  # WRITE TO REPORT FILE ----
  if(REPORT){
    write("\\subsection*{PCA}\n",file = report_PATH, append = T)

    TEXT <- "PCA was done with the module analysis output.\\\\"
    write(TEXT,file = report_PATH, append = T)


    # PCA files
    FILES <- c(paste(outPath,"/PCA/pca_var",figType_report,sep=""),paste(outPath,"/PCA/pca_plot",figType_report,sep=""))
    Captions <- c("Cumulative variance captured by principal components","Princial component scatter plot")
    FIGURE <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                    "}\\label{fig:",FILES,"}\\end{figure}",sep="")
    write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)
  }

  ### PLOT FACTOR OVER SCATTER ----

  if(!is.null(FACTOR)){
    if(REPORT){
      TEXT <- "Grouping ``factors'' were used to look at the data. The mean Euclidean distance ($m$) across the groups generated by factoring was calculated
    according to the following equation:\n \\begin{equation} m =  \\frac{\\sum_i^N d_i}{N}\\end{equation} where $N$ is the total number of distances between $p$ points, given by
      \\begin{equation} N = \\frac{p*(p-1)}{2} \\end{equation}\n and are contained in the (module\\_mean\\_dist\\_output\\_FACTOR.rda object)\\\\"
      write(TEXT,file = report_PATH, append = T)
    }

    # SCATTER PLOT
    plot_scatter_output <- plot_scatter_byFactors(pca$x,FACTOR,Filename = paste(outPath,"/PCA/plot_scatter",figType,sep=""),
                                                  xLab = paste("PC1 (",format(pca$sdev[1]*100,digits = 4),"%)",sep=""),
                                                  yLab = paste("PC2 (",format(pca$sdev[2]*100,digits = 4),"%)",sep=""))
    plot_scatter_output_file <- plot_scatter_output[[G]]$file#[grep(figType_report,plot_scatter_output[[G]]$file)]

    # MEAN DISTANCE
    module_mean_dist_output_FACTOR <- analysis_pca_mean_distance_grouping(pca$x,FACTOR, Filename = paste(outPath,"/PCA/plot_mean_dist",figType,sep=""),...)
    save(module_mean_dist_output_FACTOR,file = paste(outPath,'/PCA/module_mean_dist_output_FACTOR.rda',sep=""))

    nGroups <- numeric(length(FACTOR))
    for(G in 1:length(FACTOR)) nGroups[G] <- plot_scatter_output[[G]]$nGroups

    # WRITE FACTOR TABLE
    if(REPORT){
      TEXT <- xtable::xtable(data.frame(Factors = names(plot_scatter_output),n_Groups = nGroups),caption = "Number of groups by factors",label = "tab:Factors")
      xtable::print.xtable(TEXT, file = report_PATH, append = T,include.rownames = FALSE)

      for(G in 1:length(plot_scatter_output)){
        # INDICATE FACTOR
        write(paste("\\subsubsection*{", names(plot_scatter_output)[G], "}",sep=""),file = report_PATH, append = T)
        # write(paste(plot_scatter_output[[G]]$nGroups,"groups\\\\"),file = report_PATH, append = T)

        # PC scatter
        FILES     <- plot_scatter_output_file#paste(outPath,"/module_mean_",factor_labs,figType_report,sep="")
        Captions  <- paste(names(plot_scatter_output)[G],":  PC plot",sep="")
        FIGURE    <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                           "}\\label{fig:",FILES,"}\\end{figure}",sep="")
        write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)

        # PC mean dist
        FILES     <- module_mean_dist_output_FACTOR[[G]]$mean_dist_file#paste(outPath,"/module_mean_",factor_labs,figType_report,sep="")
        Captions  <- paste(names(plot_scatter_output)[G],":  mean Euclidean distance",sep="")
        FIGURE    <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                           "}\\label{fig:",FILES,"}\\end{figure}",sep="")
        write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)



        # FILES <- c(plot_scatter_output_file,module_mean_dist_output_FACTOR[[G]]$mean_dist_file)
        # Captions <- c(paste(names(plot_scatter_output)[G],": PCA scatter plot"),paste(names(plot_scatter_output)[G],"mean distance"))
        # if(exists(module_mean_dist_output_FACTOR[[G]]$mean_dist_file_tail)){
        if(is.element("mean_dist_file_tail",names(module_mean_dist_output_FACTOR[[G]]))){
          FILES <- module_mean_dist_output_FACTOR[[G]]$mean_dist_file_tail
          Captions <- paste(names(plot_scatter_output)[G],": PC mean distance tail",sep="")
          FIGURE <- paste("\\begin{figure}\\centering\n\\includegraphics[width=\\textwidth]{",FILES,"}\n\\caption{",Captions,
                "}\\label{fig:",FILES,"}\\end{figure}",sep="")
          write(paste(FIGURE,collapse = "\n"),file = report_PATH, append = T)
        }

        if(!is.null(plot_scatter_output[[G]]$table)){
          TEXT <- xtable::xtable(plot_scatter_output[[G]]$table,caption = names(plot_scatter_output)[G],
                                 label = paste("tab:",gsub(" ","",names(plot_scatter_output)[G]),sep=""))
          xtable::print.xtable(TEXT, file = report_PATH, append = T,include.rownames = FALSE)
        }
      }
    }
  }
### Phylogenetic tree ----
  # Best module to plot phylogenetic tree???

  ### FINALISE REPORT ----
  if(finalise_report&&REPORT){
    write("\\end{document}",file = report_PATH,append = TRUE)

    # EDIT REPORT FILE
    REPORT_FILE <- scan(file = report_PATH,what = "character",sep = "\n",quiet = T)
    # grep(paste(saveHere,"/",sep=""),REPORT_FILE)
    REPORT_FILE <- gsub(paste(outPath,"/",sep=""),"",REPORT_FILE)
    REPORT_FILE <- gsub("\\\\subsection","\\\\FloatBarrier\n\\\\subsection",REPORT_FILE)
    REPORT_FILE <- gsub("\\\\subsubsection","\\\\FloatBarrier\n\\\\subsubsection",REPORT_FILE)
    REPORT_FILE <- gsub("\\\\section","\\\\FloatBarrier\n\\\\section",REPORT_FILE)
    REPORT_FILE <- gsub("=\\\\textwidth","=0.85\\\\textwidth",REPORT_FILE)


    # WRITE
    write(REPORT_FILE[1],file = report_PATH,append = F)
    for(L in 2:length(REPORT_FILE)) write(REPORT_FILE[L],file = report_PATH,append = T)
  }


### PLOTS ----
  module_output_plots    <- list("P_allOrgs" = P_allOrgs)
  if(exists("P_allOrgs_Subset")) module_output_plots$P_allOrgs_Subset <- P_allOrgs_Subset

  # if(byGenus == T) {
  #   module_output_plots$P_genus     <- P_genus
  #   module_output_plots$P_genus_sd <- P_genus_sd
  #
  # }
  # if(bySpecies == T) {
  #   module_output_plots$P_species     <- P_species
  #   module_output_plots$P_species_sd <- P_species_sd
  # }
  while(dev.cur()>1) dev.off()
  save(module_output_plots, file = paste(outPath,"/module_output_plots.rda",sep=""))

}
