#' Parse the KEGG enzyme database
#'
#' Read the KEGG enzyme database text file and format it into a reference table.
#'
#' @details
#' The columns are automatically generated by the \code{parseKEGG_file} function into variables,
#' which are further formatted specifically for the KEGG enzyme database.
#'
#' The text file used is "\code{KEGG_path}/ligand/enzyme/enzyme".
#'
#' It decompresses "\code{KEGG_path}/ligand/enzyme.tar.gz" if needed.
#'
#' @param KEGG_path - string pointing to the location of the KEGG database parent folder. The path to the required file is contained within the function.
#'
#' @param outDir    - string pointing to the output folder. Default ("output/").
#'
#' @param verbose   - logical. Should progress be printed to the screen? Default (\code{TRUE})
#'
#' @param ...       - further arguments for \code{parseKEGG_file()}.
#'
#' @return Generates enzyme_reference_table (.txt & .rda; saved to \code{'outDir'}) and returns
#' a data frame with as many rows as entries and the following columns (or variables):
#' \preformatted{
#' 	 (1) ID         - Enzyme Commission (EC) number (e.g. "1.1.1.1"; 4 positions);
#' 	 (2) NAME       - enzyme name(s);
#' 	 (3) CLASS_I    - enzyme class; refers to the first position.
#' 	                   CLASSES:
#' 	                    1. Oxidoreductases, 2. Transferases, 3. Hydrolases,
#' 	                    4. Lyases,          5. Isomerases,   6. Ligases
#' 	 (4) CLASS_II   - further enzyme class info; refers to the second position
#' 	                   (different for every class);
#' 	 (5) CLASS_III  - further enzyme class info; refers to the third  position
#' 	                   (different for every class);
#' 	 (6) SYSNAME    - alternative names;
#' 	 (7) REACTION   - reaction(s) the enzyme catalyses;
#' 	 (8) ALL_REAC   - reaction ID(s) (R number);
#' 	 (9) SUBSTRATE  - substrate name and ID(s);
#' 	 (10) PRODUCT   - product   name and ID(s);
#' 	 (11) COMMENT; 	   (12) HISTORY; 	 (13) REFERENCE;
#' 	 (14) PATHWAY   - pathway(s) in which the enzyme is involved (ec### and name);
#' 	 (15) ORTHOLOGY - related KEGG Ortholog(s) (K number; K##### and name);
#' 	 (16) GENES; 	     (17) DBLINKS;
#'
#'  *In all instances, multiple entries in a given column are separated by '[;]'.
#' }
#'
#' @examples
#'
#' KEGG_path <- "~/KEGG" # MODIFY TO KEGG PARENT FOLDER!
#' # The parent folder should contain the following (KEGG FTP structure):
#' #	brite/
#' #	genes/
#' #	ligand/
#' #	medicus/
#' #	module/
#' #	pathway/
#' #	README.kegg
#' #	RELEASE
#' #	xml/
#'
#' enzyme_reference_table <- parseKEGG_enzyme(KEGG_path)
#'  # A .txt file (tab separated) is written to output/ (relative to current working directory)
#'
#' @seealso \link{parseKEGG_file}
#'
#' @export

################################ STEPS ########################################################
# 1.    MANAGE INPUT  - format paths and check/make outDir
# 2.    PROCESS FILE  - path structure to file self-contained as per KEGG data structure
#         Uses - parseKEGG_file() & 'KEGG_path/ligand/enzyme/enzyme'
# 3.    FORMAT TABLE
# 3.1     ENTRY (column 1) changed to ID and contains only enzyme numbers (#.#.#.#)
# 3.2     Split CLASS into 3 classes
# 4.    WRITE TABLE  (.txt, .rda)
##############################################################################################

parseKEGG_enzyme <- function(KEGG_path, outDir = "output", verbose = T,...){

  ####  MANAGE INPUT ----
  # CHECKS
  stopifnot(is.character(KEGG_path),length(KEGG_path)==1,dir.exists(KEGG_path))
  stopifnot((is.character(outDir)&&length(outDir)==1)||is.null(outDir))
  stopifnot(is.logical(verbose))

  # PATHS
  KEGG_path <- gsub("/$","",KEGG_path)
  if(!is.null(outDir)) outDir    <- gsub("/$","",outDir)

  # OUTPUT FOLDER
  if(!is.null(outDir)) if(!dir.exists(outDir)) dir.create(outDir)

  ####  PROCESS FILE ----
  if(verbose) cat("\tenzyme processing...",fill = T)
  start <- Sys.time()

  ####  UNTAR FILE ----
  if(!file.exists(paste(KEGG_path,"/ligand/enzyme",sep=""))) {
    if(verbose) cat("\n\t\tDecompressing enzyme file...",fill = T)
    untar(paste(KEGG_path,"/ligand/enzyme.tar.gz",sep=""),exdir = paste(KEGG_path,"/ligand/",sep=""))
    remove_dir <- TRUE
  } else {
    remove_dir <- FALSE
  }

  ####  PROCESS FILE ----
  enzyme_file             <- paste(KEGG_path,"/ligand/enzyme/enzyme",sep="")
  # PROCESS FILE INTO DATA FRAME
  enzyme_reference_table  <- parseKEGG_file(enzyme_file,verbose = verbose,...)

  ####  FORMAT TABLE                    ----
  enzyme_reference_table$ENTRY      <- gsubfn::strapplyc(pattern = "EC (.*) [A-Z]",enzyme_reference_table$ENTRY,simplify = T)
  names(enzyme_reference_table)[1]  <- "ID"

  #####   SPLIT CLASSES              ----
  CLASSES <- data.frame(CLASS_I   = character(nrow(enzyme_reference_table)),
                        CLASS_II  = character(nrow(enzyme_reference_table)),
                        CLASS_III = character(nrow(enzyme_reference_table)),
                        stringsAsFactors = F)

  for(j in 1:nrow(enzyme_reference_table)) CLASSES[j,] <- gsub("^ ","",strsplit(enzyme_reference_table$CLASS[j],split = ";")[[1]][1:3])

  class_col_index <- which(names(enzyme_reference_table)=="CLASS")
  if(class_col_index!=ncol(enzyme_reference_table))
    enzyme_reference_table <- cbind(enzyme_reference_table[,1:(class_col_index-1)],CLASSES,enzyme_reference_table[,(class_col_index+1):ncol(enzyme_reference_table)])

  if(class_col_index==ncol(enzyme_reference_table))
    enzyme_reference_table <- cbind(enzyme_reference_table[,1:(class_col_index-1)],CLASSES) # unlikely

  #### WRITE REFERENCE TABLE ----
  enzyme_reference_table_file <- paste(outDir,"/enzyme_reference_table.txt",sep="")

  if(!is.null(outDir)) {
    write.table(enzyme_reference_table,file = enzyme_reference_table_file,sep = "\t",row.names = F,quote = F)
    save(enzyme_reference_table,file = gsub(".txt",".rda",enzyme_reference_table_file))
  }
  if(verbose) cat("\t Completed in",format(difftime(Sys.time(),start,units = "mins"),digits = 4),"\n",fill = T)

  # if(remove_dir) unlink(paste(KEGG_path,"/ligand/enzyme/",sep=""),recursive = T, force = T)

  ### RETURN ---
  return(enzyme_reference_table)
}
